enable:
  issues: false
  prs: true

labels:
  'bug':
    include:
      - '\bfix\b'
  'enhancement':
    include:
      - '\bfeat\b'
  'documentation':
    include:
      - '\bdocs\b'
  'release':
    include:
      - '\brelease\b'
  'refactoring':
    include:
      - '\brefactor\b' 
  'test':
    include:
      - '\btest\b' 
  '1조':
    include:
      - '\b1조\b' 
  '11조':
    include:
      - '\b11조\b'
